repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6 # use 2.8.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.0

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 35.23.2
    hooks:
      - id: renovate-config-validator
