repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.13.0
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # use 2.8.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.0

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 38.142.7
    hooks:
      - id: renovate-config-validator
